import type { Metadata } from 'next'
import {JetBrains_Mono} from 'next/font/google'
import "./global.scss";
import StoreProvider from "@/app/StoreProvider";
import {StyledEngineProvider} from "@mui/styled-engine";
import SwipeMenu from "@/components/SwipeMenu";

const jetBrains_Mono = JetBrains_Mono({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jetBrains_Mono.className}>
        <StoreProvider>
          <StyledEngineProvider injectFirst>
            <SwipeMenu/>
            {children}
          </StyledEngineProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
